include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse Configuration Library
LUCI_DEPENDS:=+luci-base +luci-lib-httpclient +morse-regdb

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature