#
# Copyright (C) 2014-2022 Chart.js Contributers
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Chart.js library
LUCI_MAINTAINER:=Morse Micro
LUCI_URL:=https://www.chartjs.org/
LUCI_SUBMENU:=6. Libraries
LUCI_DESCRIPTION:=minified ChartJS 4 javascript library

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
