#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

SERVICE=prplmesh

stop_service() {
        /opt/prplmesh/scripts/prplmesh.init stop
}

start_service() {
	procd_open_instance
	procd_set_param command /opt/prplmesh/scripts/prplmesh.init start
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
        stop
        sleep 5
        start
}


service_triggers() {
	procd_add_reload_trigger "prplmesh" "network" "wireless"
}
