#!/bin/sh

/etc/init.d/lighttpd disable

sed -i 's|tr181-httpaccess -D|mkdir -m 0775 -p /var/log/lighttpd; chgrp www-data /var/log/lighttpd; tr181-httpaccess -D|' /etc/init.d/tr181-httpaccess

exit 0
