include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse Configuration
LUCI_DEPENDS:=+luci-base +luci-lib-morseconfig +luci-lib-morseui +umdns

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature