#!/bin/sh 

[ "$(uci -q get network.ahwlan.defaults_applied)" = "1" ] && exit 0

uci set network.ahwlan="interface"
uci set network.ahwlan.proto="static"
uci set network.ahwlan.ipaddr="192.168.1.1"
uci set network.ahwlan.netmask="255.255.255.0"

uci commit network

uci set network.ahwlan.defaults_applied="1"
uci commit network
