#!/bin/sh 

[ "$(uci -q get dhcp.data.defaults_applied)" = "1" ] && exit 0

# Remove default instances
while uci -q delete dhcp.@dnsmasq[0]; do :; done
while uci -q delete dhcp.@dhcp[0]; do :; done

# Use network interface names for DHCP/DNS instance names
INST="lan ahwlan privlan"
for INST in ${INST}
do
uci set dhcp.${INST}_dns="dnsmasq"
uci set dhcp.${INST}_dns.domainneeded="1"
uci set dhcp.${INST}_dns.boguspriv="1"
uci set dhcp.${INST}_dns.filterwin2k="0"
uci set dhcp.${INST}_dns.localise_queries="1"
uci set dhcp.${INST}_dns.rebind_protection="1"
uci set dhcp.${INST}_dns.rebind_localhost="1"
uci set dhcp.${INST}_dns.local="/${INST}/"
uci set dhcp.${INST}_dns.domain="${INST}"
uci set dhcp.${INST}_dns.expandhosts="1"
uci set dhcp.${INST}_dns.nonegcache="0"
uci set dhcp.${INST}_dns.authoritative="1"
uci set dhcp.${INST}_dns.readethers="1"
uci set dhcp.${INST}_dns.leasefile="/tmp/dhcp.leases.${INST}"
uci set dhcp.${INST}_dns.nonwildcard="1"
uci add_list dhcp.${INST}_dns.interface="${INST}"
uci add_list dhcp.${INST}_dns.notinterface="loopback"

# These disable the dns server
uci set dhcp.${INST}_dns.localuse="0"
uci set dhcp.${INST}_dns.port="0"

uci set dhcp.${INST}="dhcp"
uci set dhcp.${INST}.instance="${INST}_dns"
uci set dhcp.${INST}.interface="${INST}"
uci set dhcp.${INST}.start="100"
uci set dhcp.${INST}.limit="150"
uci set dhcp.${INST}.leasetime="12h"
#This disables the dhcp server
uci set dhcp.${INST}.ignore="1"
done

uci set dhcp.privlan.ignore="0"
uci set dhcp.ahwlan.ignore="0"
uci add_list dhcp.ahwlan.dhcp_option="3,192.168.1.1"
uci add_list dhcp.ahwlan.dhcp_option="6,192.168.1.1"
uci add_list dhcp.privlan.dhcp_option="3,10.42.0.1"
uci add_list dhcp.privlan.dhcp_option="6,10.42.0.1"

uci -q delete dhcp.@dnsmasq[0].notinterface
uci commit dhcp

uci set dhcp.data='defaults'
uci set dhcp.data.defaults_applied='1'
uci commit dhcp

/etc/init.d/dnsmasq restart
