include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Morse UI Library
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature